### ISSUE TITLE
Warning: ReactCreditCards: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by fbuyuk** [felquis/react-credit-cards-2#11]
Warning: ReactCreditCards: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by felquis** [comment]
@fbuyuk please try version 1.0.0 and let us know if the Warning persists

**Comment by fbuyuk** [comment]
fixed
