### ISSUE TITLE
Broken imports in the README due to mismatch of the new dist folder

### ISSUE THREAD

**Issue by SeanCassiere** [felquis/react-credit-cards-2#12]
The new bundling places all the built code into a `/dist/` folder.
Accordingly, the imports in the README for provided stylesheets need to be updated to reflect the change.

Old: `import from 'react-credit-cards-2/es/styles-compiled.css'`
New: `import from 'react-credit-cards-2/dist/es/styles-compiled.css'`

Old: `import from 'react-credit-cards-2/lib/styles.scss'`
New: `import from 'react-credit-cards-2/dist/lib/styles.scss'`

Alternatively, we could work around and bundle the code into the root directory (instead of the dist folder), to retain the imports in a working state. This approach does end up making the local dev experience a bit *uglier* though.

**Comment by SeanCassiere** [comment]
@felquis your thoughts on which path you want to go down.

**Comment by SeanCassiere** [comment]
That's perfect, your patch was path 1.

This happened due to an oversight on my part in how the build step was working. I used the general convention of placing the bundled code into a `/dist` folder, that I forgot the fact that the package originally did not have such a file structure for the final bundled/shipped code.

All-in-all this was a mistake I should have seen coming.

The good news is, that it's not a change to the actual source code, rather just a few changes in the `package.json` and some other `utils` in the build stage to bring it back to it's previous state.

**Comment by felquis** [comment]
Let me know if there's anything else related to this to be fixed.

**Comment by SeanCassiere** [comment]
Nothing else is there for this, I'll put up a PR with a fix for this soon. Hopefully, this should not affect anyone else, for more than a few hours after the `1.0.0` release.

**Comment by felquis** [comment]
@SeanCassiere I'm ok leaving it as `dist/es` it's an easy fix, people will need to manually opt-in 1.0 anyway.

**Comment by SeanCassiere** [comment]
@felquis Cool stuff.
PR #13 can be disregarded then.
