### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by semihraifgurel** [felquis/react-credit-cards-2#15]
```
WARNING in ./node_modules/react-credit-cards-2/dist/es/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/user/project/node_modules/react-credit-cards-2/src/ReactCreditCards.tsx' file: Error: ENOENT: no such file or directory, open '/Users/user/project/node_modules/react-credit-cards-2/src/ReactCreditCards.tsx'

WARNING in ./node_modules/react-credit-cards-2/dist/es/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/user/project/node_modules/react-credit-cards-2/src/utils/cardHelpers.ts' file: Error: ENOENT: no such file or directory, open '/Users/user/project/node_modules/react-credit-cards-2/src/utils/cardHelpers.ts'

WARNING in ./node_modules/react-credit-cards-2/dist/es/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/user/project/node_modules/react-credit-cards-2/src/utils/cardTypes.ts' file: Error: ENOENT: no such file or directory, open '/Users/user/project/node_modules/react-credit-cards-2/src/utils/cardTypes.ts'

```

**Comment by semihraifgurel** [comment]
Does anyone else have this problem?

**Comment by semihraifgurel** [comment]
[https://www.npmjs.com/package/react-credit-cards-2?activeTab=code](https://www.npmjs.com/package/react-credit-cards-2?activeTab=code)
You can check it out with the [link](https://www.npmjs.com/package/react-credit-cards-2?activeTab=code).

**Comment by semihraifgurel** [comment]
You can test it [here (https://github.com/omtanke/react-credit-cards-2-test)](https://github.com/omtanke/react-credit-cards-2-test). New and empty project created for this.

**Comment by matheusnunesismael** [comment]
Any update? I have the same problem

**Comment by semihraifgurel** [comment]
@felquis is there any update?

**Comment by michaelvilarino** [comment]
Any fixes for this problem?
I'm going through the same situation!

**Comment by felquis** [comment]
Hey @semihraifgurel I'm around, Thank you for this link https://github.com/felquis/react-credit-cards-2/issues/15#issuecomment-1521724546

Looks like your repo works, but it can't find sourcemaps. We should doublecheck we are shipping the lib with sourcemaps enabled and try again.

**Comment by leineveber** [comment]
still facing it, it's trying to find it inside "src" folder of library, but there is no "src"
<img width="1322" alt="image" src="https://github.com/felquis/react-credit-cards-2/assets/75081833/84a14033-debf-4aeb-ad93-01afb4cee8b8">
<img width="289" alt="image" src="https://github.com/felquis/react-credit-cards-2/assets/75081833/2eff291e-cba8-4d3f-882c-0426fb72f1be">

**Comment by jayademola** [comment]
Still facing the issue

**Comment by Johnne25** [comment]
Although this doesn't seem to be effecting functionality is it possible to get a fix for this warning?

**Comment by kevin-kuhn** [comment]
Is there any fix for it? I'm also facing the issue

**Comment by felquis** [comment]
@kevin-kuhn can you try react-credit-cards-2@2.0.0-rc1 and let me know if this error still happens?
