### ISSUE TITLE
Could not find a declaration file for module 'react-credit-cards-2'

### ISSUE THREAD

**Issue by gp-fgutierrez** [felquis/react-credit-cards-2#7]
Hi guys, I'm getting this error when trying to import `Cards`

![image](https://user-images.githubusercontent.com/112872403/210782123-d8c33c29-529e-40b2-bf3c-8318789a11fb.png)

Any though?

**Comment by smooth-lee** [comment]
I also solved the problem as below.

However, the solution I proposed is not a good one.

`react-credit-cards-2.d.ts`

Create a file with the name above and create the following:

`Declares module 'credit-credit-cards-2';`

I hope you found it helpful. Thank you.

**Comment by felquis** [comment]
@smooth-lee how do we solve this problem in this source?

Thank you for sharing @gp-fgutierrez

**Comment by yangricardo** [comment]
I recently discovered this library, would be nice to have Typescript support

**Comment by felquis** [comment]
@yangricardo I believe we can start adding this suggestion https://github.com/felquis/react-credit-cards-2/issues/7#issuecomment-1372263106?

cc @SeanCassiere had plans to introduce typescript

**Comment by yangricardo** [comment]
> @yangricardo I believe we can start adding this suggestion [#7 (comment)](https://github.com/felquis/react-credit-cards-2/issues/7#issuecomment-1372263106)?
> 
> cc @SeanCassiere had plans to introduce typescript

Yeah,
I recently had to use it in nextjs with dynamic import and to import using typescript notation i defined something similar to this based on this [props](https://github.com/felquis/react-credit-cards-2#props)
```typescript
type CardsProps = {
  name: string; //name {string}: Name on card. *
  number: string; // number {string|number}: Card number. *
  expiry: string | number; //{string|number}: Card expiry date. 10/20 or 012017 *
  cvc: string | number; //  {string|number}: Card CVC/CVV. *
  focused?: 'name'|'number'|'expiry'|'cvc' //{string}: Focused card field. name|number|expiry|cvc 
  locale: unknown; // should be defined  {object}: Localization text (e.g. { valid: 'valid thru' }).
  placeholders: unknown; // should be defined {object}: Placeholder text (e.g. { name: 'YOUR NAME HERE' }).
  preview: boolean; // {bool}: To use the card to show scrambled data (e.g. **** 4567).
  issuer: string; // {string}: Set the issuer for the preview mode (e.g. visa|mastercard|...)
  acceptedCards: string[]; // {array}: If you want to limit the accepted cards. (e.g. ['visa', 'mastercard']
  callback: (args:unknown[])=>unknown; // {func}: A callback function that will be called when the card number has changed with 2 paramaters: type ({ issuer: 'visa', maxLength: 19 }), isValid ({boolean})
}
```

**Comment by SeanCassiere** [comment]
> @yangricardo I believe we can start adding this suggestion [#7 (comment)](https://github.com/felquis/react-credit-cards-2/issues/7#issuecomment-1372263106)?
> 
> cc @SeanCassiere had plans to introduce typescript

Sorry, I migrated to another country and life kind of took over.

I'd done quite a bit of the migration. Will make a PR soon.

**Comment by SeanCassiere** [comment]
PR is up.
https://github.com/felquis/react-credit-cards-2/pull/10

**Comment by felquis** [comment]
Just released the PR above, try version 1.0.0 and let us know if this issue can be closed.

cc @gp-fgutierrez @smooth-lee @yangricardo

**Comment by yangricardo** [comment]
Testing right now, congrats for the work about the Typescript support, changing my old type and  adopting yours =D

On the other hand,  the callback data is returning some unexpected responses, not sure if is some render problem, but i expected that this callback were activated each time i update some card number... The card number i used is a common card for testing purposes, that visually, is corrected assumed to be issuered by Visa
![image](https://user-images.githubusercontent.com/5523565/229952635-717d2d43-d9b5-478f-bafb-5ea10ecb8668.png)

**Comment by felquis** [comment]
@yangricardo  Thank you for reporting

if you can please create a new issue regarding this problem - I'll casually mention @SeanCassiere about this https://github.com/felquis/react-credit-cards-2/issues/7#issuecomment-1496775340

**Comment by felquis** [comment]
Closing this issue because the declaration file not found is not a problem anymore.
