### ISSUE TITLE
npm needs new version published

### ISSUE THREAD

**Issue by dlong500** [felquis/react-credit-cards-2#8]
The project repository and homepage links in the currently available npm release are pointing to non-existent pages.  It looks like the links have been updated in the `package.json` file but there hasn't been a release pushed to npm for 7 months so the registry is still using the old non-functional links.

**Comment by felquis** [comment]
Thank you for noticing it, I'll publish a new version tomorrow.

**Comment by dlong500** [comment]
Just bumping this again.  I know it's a pretty minor issue.

**Comment by felquis** [comment]
Hey @dlong500,
check it out https://www.npmjs.com/package/react-credit-cards-2 
Anything else I'm missing?

https://github.com/felquis/react-credit-cards-2/pull/9

**Comment by dlong500** [comment]
Looks good.  Thanks!
